= What’s New in Oracle JDK 9

https://docs.oracle.com/javase/9/whatsnew/toc.htm[英文原文]

E77563-05

September 2017

== Overview of  What’s New in JDK 9
JavaSE 9 是一个大版本. 下边是 Oracle JavaSE 9 及 JDK 9 的一些特性及改进。

一条 JEP 是为 JDK 设计及实现改进的提议。
http://openjdk.java.net/jeps/1[查看 JEP 1: JDK 改进提议及处理流程。]
JSR 描述了对 Java 平台的提议及最终确认的标准。
https://www.jcp.org/en/jsr/overview[看 JSR 介绍。]

== JDK 9 中的关键改变
These changes affect more than one technology area.
这些改变影响多种技术领域。

|===
|特性 |说明
|Java 模块系统 |Java 模块化系统引入了一种新的编程组件 —— 模块，模块自声明了一系列代码及数据。模块系统：

* 在编译阶段及运行阶段引入新的阶段（可选）——链接过程，此阶段一系列模块可以组装并优化成特定的运行时镜像（image);
查看 JavaSE 工具参考中的 https://docs.oracle.com/javase/9/tools/jlink.htm[jlink] 工具说明。

* javac、jlink、java 等工具都增加了模块路径选项，指明模块定义位置。

* 引入模块化 JAR 文件，JAR 文件根目录中的 module-info.class 文件。

* 引入 JMOD 格式，类似 JAR 的一个打包格式，但是 JMOD 可以打包原生代码及配置文件；查看 jmod 工具。(TODO)
The JDK itself has been divided into a set of modules. This change:


JDK 本身也拆分成了一系列模块，包括：

* 支持 JDK 模块组合成多种配置，包括：
    * JRE 及 JDK 对应配置。
    * 近似 Java SE 8 中定义的 http://openjdk.java.net/jeps/161[紧凑模式]。
    * 只包含特定模块及相关模块的定制配置。
* 为容纳模块及提升性能、安全及可维护性，重新组织 JDK 及 JRE 运行镜像。

* 为避免暴露存储在镜像中的命名模块、类、资源内容的结构或格式，定义新的 URI 模式。

* 删除 endorsed-standards 重载及扩展机制。

* 从 Java 运行时镜像中删除 `rt.jar` 及 `tools.jar` 。

* JDK 内部 API 默认不可访问，一些关键、广泛使用的会直到大部分功能有替代品时不可访问。
    运行命令 `jdeps -jdkinternals` 检查你的代码使用了哪些 JDK 内部 API。

更多信息请参阅：

* http://openjdk.java.net/projects/jigsaw/spec/[Java 模块系统]

* http://openjdk.java.net/jeps/261[JEP 261: 模块系统]

* http://openjdk.java.net/jeps/200[JEP 200: JDK 模块化]

* http://openjdk.java.net/jeps/220[JEP 220: 运行时镜像模块化]

* http://openjdk.java.net/jeps/260[JEP 260: 封闭大多数内部 API]


|JEP 223: 新的版本号编码方式
|
提供简单的版本号格式明确区分主版本、小版本、安全版本及修正版本更新发布


新的版本号格式如：
$MAJOR.$MINOR.$SECURITY.$PATCH

$MAJOR 在主版本发布时增加。
如 JDK 9, 包含大量的 Java SE 标准指定的新特性。
主版本包含很早就计划并公布要增加的新特性及现有特性修改。

$MINOR 在小版本更新时增加，如问题修正，标准 API 修正，或者实现 Java 之外标准。

$SECURITY 在安全更新发布时增加，包含关键修正及提升安全性修改。


$PATCH 是包含安全及经过测试的高优先级客户的问题修正。

查看 JavaSE 安装指南中的 https://docs.oracle.com/javase/9/install/version-string-format.htm[新版本号格式]
|===


== JDK 9 安装程序更新

JDK 9 增强了 Microsoft Windows 及 macOS 平台安装程序。


Microsoft Windows 安装程序增强
|===
|特性	|说明
|安装程序界面中可以启用或禁用 Web Deployment
|在安装程序欢迎页提供启用或禁用 Web Deployment 选项。
要启用 Web Deployment ，在欢迎页面选择定制安装，点击安装后在浏览器复选框中选择启用 Java 内容。
|===

macOS 安装程序增强

|===
|Feature	|Description
|CPU 版本号
|卸载当前 CPU 版本后新 CPU 版本可用时提供通知。

|用户体验
|提升 JRE 升级用户体验。
|===

== JDK 9 工具更新
JDK 9 中这些工具有增强。
|===
|特性	|说明

|JEP 222: jshell: Java 命令行 (Read-Eval-Print Loop)(**老唐：直接输入 jshell 进入命令行模式，可以写简单的代码直接允许)
|Java 平台增加了 Read-Eval-Print Loop (REPL) 功能。

`jshell` 工具提供了命令行接口用于执行 Java 语言的声明、语句及表达式

jshell 即时反馈能方便原型试验及探索代码不同参数选项。

即时反馈加上启动表达式对于学习 Java 语言或者新的 API 或新特性都很有帮助。

参考 JavaSE 工具参考中的 https://docs.oracle.com/javase/9/tools/jshell.htm[jshell] ，及 JavaSE Java Shell 用户指南中的 https://docs.oracle.com/javase/9/jshell/introduction-jshell.htm[JShell 介绍]

The JShell API enables applications to leverage REPL functionality. See the jdk.jshell package.

JShell API 允许应用程序借助 REPL 功能。参考 https://docs.oracle.com/javase/9/docs/api/jdk.jshell-summary.html[jdk.jshell] 包.

|JEP 228: Add More Diagnostic Commands
|Defines additional diagnostic commands to improve the ability to diagnose issues with Hotspot and the JDK.

See jcmd in Java Platform, Standard Edition Tools Reference.

|JEP 231: Remove Launch-Time JRE Version Selection
|Removes the ability to request a version of the JRE that is not the JRE being launched at launch time.

Modern applications are typically deployed through Java Web Start (with a JNLP file), native OS packaging systems, or active installers. These technologies have their own methods to manage the JREs needed by finding or downloading and updating the required JRE as needed. This makes launch-time JRE version selection obsolete.

|JEP 238: Multi-Release JAR Files
|Extends the JAR file format to enable multiple, Java release-specific versions of class files to coexist in a single archive.

A multirelease JAR (MRJAR) contains additional, versioned directories for classes and resources specific to particular Java platform releases. Specify versioned directories with the jar tool's --release option.

|JEP 240: Remove the JVM TI hprof Agent
|Removes the hprof agent from the JDK. The hprof agent was written as demonstration code for the JVM Tool Interface and not intended to be a production tool.

The useful features of the hprof agent have been superseded by better alternatives.

Note:
While the hprof agent has been removed, it is still possible to create heap dumps in the hprof format using jmap or other diagnostic tools. See Diagnostic Tools in Java Platform, Standard Edition Troubleshooting Guide.

|JEP 241: Remove the jhat Tool
|Removes the jhat tool from the JDK.

The jhat tool was an experimental and unsupported tool added in JDK 6. It is out of date; superior heap visualizers and analyzers have been available for many years.

|JEP 245: Validate JVM Command-Line Flag Arguments
|Validates arguments to all numerical JVM command-line flags to avoid failures and instead displays an appropriate error message if they are found to be invalid.

Range and optional constraint checks have been implemented for arguments that require a user-specified numerical value.

See java and Validate Java Virtual Machine Flag Arguments in Java Platform, Standard Edition Tools Reference.

|JEP 247: Compile for Older Platform Versions
|Enhances javac so that it can compile Java programs to run on selected earlier versions of the platform.

When using the -source or -target options, the compiled program might accidentally use APIs that are not supported on the given target platform. The --release option will prevent accidental use of APIs.

See javac in Java Platform, Standard Edition Tools Reference.

|JEP 282: jlink: The Java Linker
|Assembles and optimizes a set of modules and their dependencies into a custom runtime image as defined in JEP 220.

The jlink tool defines a plug-in mechanism for transformation and optimization during the assembly process, and for the generation of alternative image formats. It can create a custom runtime optimized for a single program. JEP 261 defines link time as an optional phase between the phases of compile time and run time. Link time requires a linking tool that assembles and optimizes a set of modules and their transitive dependencies to create a runtime image or executable.

See jlink in Java Platform, Standard Edition Tools Reference.
|===

== What’s New for Security in JDK 9
These are the security enhancements in JDK 9.

Feature	Description
JEP 219: Datagram Transport Layer Security (DTLS)
Enables Java Secure Socket Extension (JSSE) API and the SunJSSE security provider to support DTLS Version 1.0 and DTLS Version 1.2 protocols.

See Datagram Transport Layer Security (DTLS) in Java Platform, Standard Edition Security Developer's Guide.

JEP 244: TLS Application-Layer Protocol Negotiation Extension

Enables the client and server in a Transport Layer Security (TLS) connection to negotiate the application protocol to be used. With Application-Layer Protocol Negotiation (ALPN), the client sends the list of supported application protocols as part of the TLS ClientHello message. The server chooses a protocol and returns the selected protocol as part of the TLS ServerHello message. The application protocol negotiation can be accomplished within the TLS handshake, without adding network round-trips.

See TLS Handshake and Application Layer Protocol Negotiation in Java Platform, Standard Edition Security Developer's Guide.

JEP 249: OCSP Stapling for TLS
Enables the server in a TLS connection to check for a revoked X.509 certificate revocation. The server does this during TLS handshaking by contacting an Online Certificate Status Protocol (OCSP) responder for the certificate in question. It then attaches or "staples" the revocation information to the certificate that it returns to the client so that the client can take appropriate action.

Enables the client to request OCSP stapling from a TLS server. The client checks stapled responses from servers that support the feature.

See OCSP Stapling in Java Platform, Standard Edition Security Developer's Guide.

JEP 246: Leverage CPU Instructions for GHASH and RSA
Improves performance ranging from 34x to 150x for AES/GCM/NoPadding using GHASH HotSpot intrinsics. GHASH intrinsics are accelerated by the PCLMULQDQ instruction on Intel x64 CPU and the xmul/xmulhi instructions on SPARC.

Improves performance up to 50% for BigInteger squareToLen and BigInteger mulAdd methods using RSA HotSpot intrinsics. RSA intrinsics apply to the java.math.BigInteger class on Intel x64.

A new security property jdk.security.provider.preferred is introduced to configure providers that offer significant performance gains for specific algorithms.

See Configuring the Preferred Provider for Specific Algorithms in Java Platform, Standard Edition Security Developer's Guide.

JEP 273: DRBG-Based SecureRandom Implementations
Provides the functionality of Deterministic Random Bit Generator (DRBG) mechanisms as specified in NIST SP 800-90Ar1 in the SecureRandom API.

The DRBG mechanisms use modern algorithms as strong as SHA-512 and AES-256. Each of these mechanisms can be configured with different security strengths and features to match user requirements.

See Generating Random Numbers in Java Platform, Standard Edition Security Developer's Guide.

JEP 288: Disable SHA-1 Certificates
Improves the security configuration of the JDK by providing a more flexible mechanism to disable X.509 certificate chains with SHA-1-based signatures.

Disables SHA-1 in TLS Server certificate chains anchored by roots included by default in the JDK; local or enterprise certificate authorities (CAs) are not affected.

The jdk.certpath.disabledAlgorithms security property is enhanced with several new constraints that allow greater control over the types of certificates that can be disabled.

See JEP 288.

JEP 229: Create PKCS12 Keystores by Default
Modifies the default keystore type from JKS to PKCS12. PKCS#12 is an extensible, standard, and widely supported format for storing cryptographic keys. PKCS12 keystores improve confidentiality by storing private keys, trusted public key certificates, and secret keys. This feature also opens opportunities for interoperability with other systems such as Mozilla, Microsoft's Internet Explorer, and OpenSSL that support PKCS12.

The SunJSSE provider supplies a complete implementation of the PKCS12 java.security.KeyStore format for reading and writing PKCS12 files.

See Key Management in Java Platform, Standard Edition Security Developer's Guide.

The keytool key and certificate management utility can create PKCS12 keystores.

See Creating a Keystore in Java Platform, Standard Edition Security Developer's Guide and keytool in Java Platform, Standard Edition Tools Reference.

JEP 287: SHA-3 Hash Algorithms
Supports SHA-3 cryptographic hash functions as specified in NIST FIPS 202.

The following additional standard algorithms are supported by the java.security.MessageDigest API: SHA3-224, SHA3-256, SHA3-384, and SHA3-512.

The following providers support SHA-3 algorithm enhancements:

SUN provider: SHA3-224, SHA3-256, SHA3-384, and SHA3-512
OracleUcrypto provider: SHA-3 digests supported by Solaris 12.0
== What’s New for Deployment in JDK 9
These are the deployment enhancements in JDK 9.

Feature	Description
Deprecate the Java Plug-in
Deprecates the Java Plug-in and associated applet technologies in Oracle's JDK 9 builds. While still available in JDK 9, these technologies will be considered for removal from the Oracle JDK and JRE in a future release.

Applets and JavaFX applications embedded in a web page require the Java Plug-in to run. Consider rewriting these types of applications as Java Web Start or self-contained applications.

See Migrating Java Applets to Java Web Start and JNLP and Self-Contained Application Packaging in Java Platform, Standard Edition Deployment Guide.

Enhanced Java Control Panel
Improves the grouping and presentation of options within the Java Control Panel. Information is easier to locate, a search field is available, and modal dialog boxes are no longer used. Note that the location of some options has changed from previous versions of the Java Control Panel.

See Java Control Panel in Java Platform, Standard Edition Deployment Guide.

JEP 275: Modular Java Application Packaging
Integrates features from Project Jigsaw into the Java Packager, including module awareness and custom runtime creation.

Leverages the jlink tool to create smaller packages.

Creates applications that use the JDK 9 runtime only. Cannot be used to package applications with an earlier release of the JRE.

See Customization of the JRE and Packaging for Modular Applications in Java Platform, Standard Edition Deployment Guide.

JEP 289: Deprecate the Applet API
Deprecates the Applet API, which is becoming less useful as web browser vendors remove support for Java browser plug-ins. While still available in JDK 9, the Applet class will be considered for removal in a future release. Consider rewriting applets as Java Web Start or self-contained applications.

See Migrating Java Applets to Java Web Start and JNLP and Self-Contained Application Packaging in Java Platform, Standard Edition Deployment Guide.

== What’s New for the Java Language in JDK 9
A few very small language changes are included in Java SE 9.

Feature	Description
JEP 213: Milling Project Coin
Identifies a few small changes:

Allow @SafeVargs on private instance methods.

Allow effectively final variables to be used as resources in the try-with-resources statement.

Allow the diamond with anonymous classes if the argument type of the inferred type is denotable.

Complete the removal, begun in Java SE 8, of the underscore from the set of legal identifier names.

Add support for private interface methods.

See Java Language Changes for Java SE 9 in Java Platform, Standard Edition Java Language Updates.

== What’s New for Javadoc in JDK 9
Javadoc enhancements include the following: a simplified Doclet API, Javadoc search, support for generating HTML5 output, and support for documentation comments in module systems.

Feature	Description
JEP 221: Simplified Doclet API
Replaces the old Doclet API with a new simplified API that leverages other standard, existing APIs. The standard doclet has been rewritten to use the new Doclet API.

Note:
The existing API and old standard doclet are available, but have not been updated to support new language features, such as modules.
JEP 224: HTML5 Javadoc
Supports generating HTML5 output. To get fully compliant HTML5 output, ensure that any HTML content provided in documentation comments are compliant with HTML5.

JEP 225: Javadoc Search
Provides a search box to the generated API documentation. Use this search box to find program elements, tagged words, and phrases within the documentation.

JEP 261: Module System
Supports documentation comments in module declarations. Includes new command-line options to configure the set of modules to be documented and generates a new summary page for any modules being documented.

== What’s New for the JVM in JDK 9
These are the JVM enhancements in JDK 9.

Feature	Description
JEP 165: Compiler Control
Provides a way to control JVM compilation through compiler directive options. The level of control is runtime-manageable and method-specific. Compiler Control supersedes, and is backward compatible, with CompileCommand.

See Compiler Control in Java Platform, Standard Edition Java Virtual Machine Guide.

JEP 197: Segmented Code Cache
Divides the code cache into distinct segments, each of which contains compiled code of a particular type, to improve performance and enable future extensions.

See java in Java Platform, Standard Edition Tools Reference.

JEP 276: Dynamic Linking of Language-Defined Object Models
Dynamically links high-level object operations at run time, such as read a property, write a property, and invoke a function, to the appropriate target method handles. It links these operations to target method handles based on the actual types of the values passed. These object operations are expressed as invokedynamic sites.

While java.lang.invoke provides a low-level API for dynamic linking of invokedynamic call sites, it doesn't provide a way to express higher level operations on objects nor methods that implement them.

With the package jdk.dynalink, you can implement programming languages whose expressions contain dynamic types (types that cannot be determined statically) and whose operations on these dynamic types are expressed as invokedynamic call sites (because the language's object model or type system doesn't closely match that of the JVM).

== What’s New for JVM Tuning in JDK 9
These are the JVM tuning enhancements in JDK 9.

Feature	Description
Improve G1 Usability, Determinism, and Performance
Enhances the Garbage-First (G1) garbage collector to automatically determine several important memory-reclamation settings. Previously these settings had to be set manually to obtain optimal results. In addition, fixes issues with the usability, determinism, and performance of the G1 garbage collector.

JEP 158: Unified JVM Logging
Introduces a common logging system for all components of the JVM.

See the -Xloggc java option in Java Platform, Standard Edition Tools Reference.

JEP 214: Remove GC Combinations Deprecated in JDK 8
Removes garbage collector (GC) combinations that were deprecated in JDK 8.

This means that the following GC combinations no longer exist:

DefNew + CMS
ParNew + SerialOld
Incremental CMS
The "foreground" mode for Concurrent Mark Sweep (CMS) has also been removed. The following command-line flags have been removed:

-Xincgc
-XX:+CMSIncrementalMode
-XX:+UseCMSCompactAtFullCollection
-XX:+CMSFullGCsBeforeCompaction
-XX:+UseCMSCollectionPassing
The command line flag -XX:+UseParNewGC no longer has an effect. ParNew can only be used with CMS and CMS requires ParNew. Thus, the -XX:+UseParNewGC flag has been deprecated and will likely be removed in a future release.

JEP 248: Make G1 the Default Garbage Collector
Makes Garbage-First (G1) the default garbage collector (GC) on 32- and 64-bit server configurations. Using a low-pause collector such as G1 provides a better overall experience, for most users, than a throughput-oriented collector such as the Parallel GC, which was previously the default.

See Garbage-First Garbage Collector in Java Platform, Standard Edition HotSpot Virtual Machine Garbage Collection Tuning Guide
JEP 271: Unified GC Logging
Reimplements Garbage Collection (GC) logging using the unified JVM logging framework introduced in JEP 158. GC logging is re-implemented in a manner consistent with the current GC logging format; however, some differences exist between the new and old formats.

See Enable Logging with the JVM Unified Logging Framework in Java Platform, Standard Edition Tools Reference.

JEP 291: Deprecate the Concurrent Mark Sweep (CMS) Garbage Collector
Deprecates the Concurrent Mark Sweep (CMS) garbage collector. A warning message is issued when it is requested on the command line, using the -XX:+UseConcMarkSweepGC option. The Garbage-First (G1) garbage collector is intended to be a replacement for most uses of CMS.

== What’s New for Core Libraries in JDK 9
Feature	Description
JEP 102: Process API Updates
Improves the API for controlling and managing operating system processes.

The ProcessHandle class provides the process's native process ID, arguments, command, start time, accumulated CPU time, user, parent process, and descendants. The class can also monitor processes' liveness and destroy processes. With the ProcessHandle.onExit method, the asynchronous mechanisms of the CompletableFuture class can perform an action when the process exits.

See Process API in Java Platform, Standard Edition Java Core Libraries Developer's Guide, java.lang.Process, and java.lang.ProcessHandle.

JEP 193: Variable Handles
Defines a standard means to invoke the equivalents of java.util.concurrent.atomic and sun.misc.Unsafe operations upon object fields and array elements.

Defines a standard set of fence operations, which consist of VarHandle static methods that enable fine-grained control of memory ordering. This is an alternative to sun.misc.Unsafe, which provides a nonstandard set of fence operations.

Defines a standard reachability fence operation to ensure that a referenced object remains strongly reachable.

JEP 254: Compact Strings
Adopts a more space-efficient internal representation for strings. Previously, the String class stored characters in a char array, using two bytes (16 bits) for each character. The new internal representation of the String class is a byte array plus an encoding-flag field.

This is purely an implementation change, with no changes to existing public interfaces.

See the CompactStrings option of the java command in Java Platform, Standard Edition Tools Reference.

JEP 264: Platform Logging API and Service
Defines a minimal logging API that platform classes can use to log messages, together with a service interface for consumers of those messages. A library or application can provide an implementation of this service to route platform log messages to the logging framework of its choice. If no implementation is provided, then a default implementation based on the java.util.logging API is used.

JEP 266: More Concurrency Updates
Adds further concurrency updates to those introduced in JDK 8 in JEP 155: Concurrency Updates, including an interoperable publish-subscribe framework and enhancements to the CompletableFuture API.

JEP 268: XML Catalogs
Adds a standard XML Catalog API that supports the Organization for the Advancement of Structured Information Standards (OASIS) XML Catalogs version 1.1 standard. The API defines catalog and catalog-resolver abstractions that can be used as an intrinsic or external resolver with the JAXP processors that accept resolvers.

Existing libraries or applications that use the internal catalog API will need to migrate to the new API to take advantage of the new features.

See XML Catalog API in Java Platform, Standard Edition Java Core Libraries Developer's Guide.

JEP 269: Convenience Factory Methods for Collections
Makes it easier to create instances of collections and maps with small numbers of elements. New static factory methods on the List, Set, and Map interfaces make it simpler to create immutable instances of those collections.

For example:
Set<String> alphabet = Set.of("a", "b", "c");
See Creating Immutable Lists, Sets, and Maps in Java Platform, Standard Edition Java Core Libraries Developer's Guide. For API documentation, see Immutable Set Static Factory Methods, Immutable Map Static Factory Methods, and Immutable List Static Factory Methods.

JEP 274: Enhanced Method Handles
Enhances the MethodHandle, MethodHandles, and MethodHandles.Lookup classes of the java.lang.invoke package to ease common use cases and enable better compiler optimizations.

Additions include:
In the MethodHandles class in the java.lang.invoke package, provide new MethodHandle combinators for loops and try/finally blocks.

Enhance the MethodHandle and MethodHandles classes with new MethodHandle combinators for argument handling.

Implement new lookups for interface methods and, optionally, super constructors in the MethodHandles.Lookup class.

JEP 277: Enhanced Deprecation
Revamps the @Deprecated annotation to provide better information about the status and intended disposition of an API in the specification. Two new elements have been added:
@Deprecated(forRemoval=true) indicates that the API will be removed in a future release of the Java SE platform.

@Deprecated(since="version") contains the Java SE version string that indicates when the API element was deprecated, for those deprecated in Java SE 9 and beyond.

For example: @Deprecated(since="9", forRemoval=true)

@Deprecated annotations in the core platform have been updated.

You can use a new tool, jdeprscan, to scan a class library (JAR file) for uses of deprecated JDK API elements.

See Enhanced Deprecation in Java Platform, Standard Edition Java Core Libraries Developer's Guide.

See jdperscan in Java Platform, Standard Edition Tools Reference.

JEP 285: Spin-Wait Hints
Defines an API that enables Java code to hint that a spin loop is executing. A spin loop repeatedly checks to see if a condition is true, such as when a lock can be acquired, after which some computation can be safely performed followed by the release of the lock. This API is purely a hint, and carries no semantic behavior requirements. See the method Thread.onSpinWait.

JEP 290: Filter Incoming Serialization Data
Allows incoming streams of object-serialization data to be filtered to improve both security and robustness. Object-serialization clients can validate their input more easily, and exported Remote Method Invocation (RMI) objects can validate invocation arguments more easily as well.

Serialization clients implement a filter interface that is set on an ObjectInputStream. For RMI, the object is exported through a RemoteServerRef that sets the filter on the MarshalInputStream to validate the invocation arguments as they are unmarshalled.

JEP 259: Stack-Walking API
Provides a stack-walking API that allows easy filtering and lazy access to the information in stack traces.

The API supports both short walks that stop at a frame that matches given criteria, and long walks that traverse the entire stack. Stopping at a frame that matches a given criteria avoids the cost of examining all the frames if the caller is interested only in the top frames on the stack. The API enables access to Class objects when the stack walker is configured to do so. See the class java.lang.Stackwalker.

JEP 255: Merge Selected Xerces 2.11.0 Updates into JAXP
Updates the JDK to support the 2.11.0 version of the Xerces parser. There is no change to the public JAXP API.

The changes are in the following categories of Xerces 2.11.0: Datatypes, DOM L3 Serializer, XPointer, Catalog Resolver, and XML Schema Validation (including bug fixes, but not the XML Schema 1.1 development code).

What's New for Nashorn in JDK 9
These are the Nashorn enhancements in JDK 9.

Feature	Description
JEP 236: Parser API for Nashorn
Enables applications, in particular IDEs and server-side frameworks, to parse and analyze ECMAScript code.

Parse ECMAScript code from a string, URL, or file with methods from the Parser class. These methods return an instance of CompilationUnitTree, which represents ECMAScript code as an abstract syntax tree.

The package jdk.nashorn.api.tree contains the Nashorn parser API.

JEP 292: Implement Selected ECMAScript 6 Features in Nashorn	Implements many new features introduced in the 6th edition of ECMA-262, also known as ECMAScript 6, or ES6 for short. Implemented features include the following:
Template strings
let, const, and block scope
Iterators and for..of loops
Map, Set, WeakMap, and WeakSet
Symbols
Binary and octal literals
== What’s New for Client Technologies in JDK 9
These are the client technologies enhancements in JDK 9.

Feature	Description
JEP 251: Multi-Resolution Images
Enables a set of images with different resolutions to be encapsulated into a single multiresolution image. This could be useful for applications to adapt to display devices whose resolutions may vary from approximately 96dpi to 300dpi during run time.

The interface java.awt.image.MultiResolutionImage encapsulates a set of images with different resolutions into a single multiresolution image, which enables applications to easily manipulate and display images with resolution variants.

JEP 253: Prepare JavaFX UI Controls and CSS APIs for Modularization
Provides public APIs for JavaFX UI controls and CSS functionality that were previously available only through internal packages but are now inaccessible due to modularization.

The new package javafx.scene.control.skin consists of a set of classes that provides a default implementation for the skin (or the look) of each UI control.

The new class CssParser is a CSS parser that returns a Stylesheet object, which gives you more control over the CSS styling of your application. It’s part of the CSS API (the javafx.css package). The CSS API includes new support classes, including a set of standard converters used by the parser; see the javafx.css.converter package.

JEP 256: BeanInfo Annotations
Replaces the @beaninfo Javadoc tag with the annotation types JavaBean, BeanProperty, and SwingContainer.

These annotation types set the corresponding feature attributes during BeanInfo generation at runtime. Thus, you can more easily specify these attributes directly in Bean classes instead of creating a separate BeanInfo class for every Bean class. It also enables the removal of automatically generated classes, which makes it easier to modularize the client library.

JEP 262: TIFF Image I/O
Adds Tag Image File Format (TIFF) reading and writing as standard to the package javax.imageio. The new package javax.imageio.plugins.tiff provides classes that simplify the optional manipulation of TIFF metadata.

JEP 263: HiDPI Graphics on Windows and Linux
Automatically scales and sizes AWT and Swing components for High Dots Per Inch (HiDPI) displays on Windows and Linux.

The JDK already supports HiDPI "retina displays" on OS X.

Prior to this release, on Windows and Linux, Java applications were sized and rendered based on pixels, even on HiDPI displays that can have pixel densities two to three times as high as traditional displays. This led to GUI components and windows that were too small to read or use.

JEP 272: Platform-Specific Desktop Features
Adds additional methods to the class java.awt.Desktop that enable you to interact with the desktop, including the following:

Show custom About and Preferences windows.
Handle requests to open or print a list of files.
Handle requests to open a URL.
Open the native help viewer application.
Set the default menu bar.
Enable or disable the application to be suddenly terminated.
These new methods replace the functionality of the internal APIs contained in the OS X package com.apple.eawt, which are not accessible by default in JDK 9. Note that the package com.apple.eio is no longer accessible.

JEP 283: Enable GTK 3 on Linux
Enables Java graphical applications, whether based on JavaFX, Swing, or Abstract Window Toolkit (AWT), to use either the GTK+ version 2 or version 3 on Linux or Solaris.

By default, the JDK on Linux or Solaris uses GTK+ 2 if available; if not, it uses GTK+ 3.

To use a specific version of GTK+, set the system property jdk.gtk.version. This system property may have a value of 2, 2.2, or 3. You must set this property before your application loads GTK+, and it must not conflict with a GTK+ version that may have been loaded earlier by another toolkit.

== What’s New for Internationalization in JDK 9
These are the internationalization enhancements in JDK 9.

Feature	Description
JEP 267: Unicode 8.0
Supports Unicode 8.0. JDK 8 supported Unicode 6.2.

The Unicode 6.3, 7.0 and 8.0 standards combined introduced 10,555 characters, 29 scripts, and 42 blocks, all of which are supported in JDK 9.

JEP 252: CLDR Locale Data Enabled by Default
Uses the Common Locale Data Repository's (CLDR) XML-based locale data, first added in JDK 8, as the default locale data in JDK 9. In previous releases, the default was JRE.

To enable behavior compatible with JDK 8, set the system property java.locale.providers to a value with COMPAT ahead of CLDR.

See CLDR Locale Data Enabled by Default in Java Platform, Standard Edition Internationalization Guide.

JEP 226: UTF-8 Properties Files
Loads properties files in UTF-8 encoding. In previous releases, ISO-8859-1 encoding was used when loading property resource bundles. UTF-8 is a much more convenient way to represent non-Latin characters.

Most existing properties files should not be affected.

See UTF-8 Properties Files in Java Platform, Standard Edition Internationalization Guide.

Documentation Accessibility
For information about Oracle's commitment to accessibility, visit the Oracle Accessibility Program website at http://www.oracle.com/pls/topic/lookup?ctx=acc&id=docacc.

Access to Oracle Support

Oracle customers that have purchased support have access to electronic support through My Oracle Support. For information, visit http://www.oracle.com/pls/topic/lookup?ctx=acc&id=info or visit http://www.oracle.com/pls/topic/lookup?ctx=acc&id=trs if you are hearing impaired.

Java Platform, Standard Edition == What’s New in Oracle JDK 9, Release 9

E77563-05

Copyright © 2017, Oracle and/or its affiliates. All rights reserved.

This document summarizes features and enhancements in Java SE 9 and in JDK 9, Oracle's implementation of Java SE 9.

This software and related documentation are provided under a license agreement containing restrictions on use and disclosure and are protected by intellectual property laws. Except as expressly permitted in your license agreement or allowed by law, you may not use, copy, reproduce, translate, broadcast, modify, license, transmit, distribute, exhibit, perform, publish, or display any part, in any form, or by any means. Reverse engineering, disassembly, or decompilation of this software, unless required by law for interoperability, is prohibited.

The information contained herein is subject to change without notice and is not warranted to be error-free. If you find any errors, please report them to us in writing.

If this is software or related documentation that is delivered to the U.S. Government or anyone licensing it on behalf of the U.S. Government, then the following notice is applicable:

U.S. GOVERNMENT END USERS: Oracle programs, including any operating system, integrated software, any programs installed on the hardware, and/or documentation, delivered to U.S. Government end users are "commercial computer software" pursuant to the applicable Federal Acquisition Regulation and agency-specific supplemental regulations. As such, use, duplication, disclosure, modification, and adaptation of the programs, including any operating system, integrated software, any programs installed on the hardware, and/or documentation, shall be subject to license terms and license restrictions applicable to the programs. No other rights are granted to the U.S. Government.

This software or hardware is developed for general use in a variety of information management applications. It is not developed or intended for use in any inherently dangerous applications, including applications that may create a risk of personal injury. If you use this software or hardware in dangerous applications, then you shall be responsible to take all appropriate fail-safe, backup, redundancy, and other measures to ensure its safe use. Oracle Corporation and its affiliates disclaim any liability for any damages caused by use of this software or hardware in dangerous applications.

Oracle and Java are registered trademarks of Oracle and/or its affiliates. Other names may be trademarks of their respective owners.

Intel and Intel Xeon are trademarks or registered trademarks of Intel Corporation. All SPARC trademarks are used under license and are trademarks or registered trademarks of SPARC International, Inc. AMD, Opteron, the AMD logo, and the AMD Opteron logo are trademarks or registered trademarks of Advanced Micro Devices. UNIX is a registered trademark of The Open Group.

This software or hardware and documentation may provide access to or information about content, products, and services from third parties. Oracle Corporation and its affiliates are not responsible for and expressly disclaim all warranties of any kind with respect to third-party content, products, and services unless otherwise set forth in an applicable agreement between you and Oracle. Oracle Corporation and its affiliates will not be responsible for any loss, costs, or damages incurred due to your access to or use of third-party content, products, or services, except as set forth in an applicable agreement between you and Oracle.
